/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>
int length = 0;
int arr<>;

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;

	printf("Server: bin_date_1 called\n");
	result = time(NULL);  // Get current time as binary value
	
	return &result;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char *result;
	static char date_string[64];
	time_t bintime;

	printf("Server: str_date_1 called with time: %ld\n", *argp);
	
	bintime = *argp;
	strcpy(date_string, ctime(&bintime));
	
	// Remove the newline character at the end
	date_string[strlen(date_string) - 1] = '\0';
	
	result = date_string;
	return &result;
}


void insert_svc(int new_element, int index){
	if (index >= 0 && index < length) {
		arr[index] = new_element;
	}
	length++;
}

int retrieve_svc(int index){
	if (index >= 0 && index < length) {
		return arr[index];
	}
	return -1;  // Meaningful value indicating out-of-bounds access
}


void delete_svc(int index){
	if (index >= 0 && index < length) {
		arr[index] = 0;  // Reset the value to 0 (or any other meaningful value)
	}
}
