/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>

#define MAX_ARRAY_SIZE 100
int length = 0;
int arr[MAX_ARRAY_SIZE];

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;

	printf("Server: bin_date_1 called\n");
	result = time(NULL);  // Get current time as binary value
	
	return &result;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char *result;
	static char date_string[64];
	time_t bintime;

	printf("Server: str_date_1 called with time: %ld\n", *argp);
	
	bintime = *argp;
	strcpy(date_string, ctime(&bintime));
	
	// Remove the newline character at the end
	date_string[strlen(date_string) - 1] = '\0';
	
	result = date_string;
	return &result;
}


void insert_svc(int new_element, int index){
	if (index >= 0 && index < length) {
		arr[index] = new_element;
	}
	length++;
}

int retrieve_svc(int index){
	if (index >= 0 && index < length) {
		return *arr[index];
	}
	return -1;  // Meaningful value indicating out-of-bounds access
}


void delete_svc(int index){
	if (index >= 0 && index < length) {
		arr[index] = 0;  // Reset the value to 0 (or any other meaningful value)
	}
}

// RPC service functions
void *
insert_array_1_svc(insert_args *argp, struct svc_req *rqstp)
{
	static char dummy_result;
	
	printf("Server: insert_array_1 called - element: %d, index: %d\n", argp->element, argp->index);
	insert_svc(argp->element, argp->index);
	
	return (void *) &dummy_result;
}

int *
retrieve_array_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	
	printf("Server: retrieve_array_1 called - index: %d\n", *argp);
	result = retrieve_svc(*argp);
	
	return &result;
}

void *
delete_array_1_svc(int *argp, struct svc_req *rqstp)
{
	static char dummy_result;
	
	printf("Server: delete_array_1 called - index: %d\n", *argp);
	delete_svc(*argp);
	
	return (void *) &dummy_result;
}
