/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include "LinkedList.h"


int length = 0;
Node *head = NULL;  // Head of the linked list


long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;

	printf("Server: bin_date_1 called\n");
	result = time(NULL);  // Get current time as binary value
	
	return &result;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char *result;
	static char date_string[64];
	time_t bintime;

	printf("Server: str_date_1 called with time: %ld\n", *argp);
	
	bintime = *argp;
	strcpy(date_string, ctime(&bintime));
	
	// Remove the newline character at the end
	date_string[strlen(date_string) - 1] = '\0';
	
	result = date_string;
	return &result;
}


void insert_svc(int new_element, int index){
	if (index < 0) {
		index = 0;  // Insert at head if index is negative
	} else if (index > length) {
		index = length;  // Append at end if index is greater than length
	}
	insert_node(&head, new_element, index);
	length++;
}

int retrieve_svc(int index){
	if (index >= 0 && index <= length) {
		Node *node = search_node(head, index);
		if (node) {
			return node->data;
		}
	}
	return -1;  // Meaningful value indicating out-of-bounds access
}


void delete_svc(int index){
	if (index >= 0 && index < length) {
		delete_node(&head, index);
		length--;
	}
}

// RPC service functions
void *
insert_array_1_svc(insert_args *argp, struct svc_req *rqstp)
{
	static char dummy_result;
	
	printf("Server: insert_array_1 called - element: %d, index: %d\n", argp->element, argp->index);
	insert_svc(argp->element, argp->index);
	
	return (void *) &dummy_result;
}

int *
retrieve_array_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;
	
	printf("Server: retrieve_array_1 called - index: %d\n", *argp);
	result = retrieve_svc(*argp);
	
	return &result;
}

void *
delete_array_1_svc(int *argp, struct svc_req *rqstp)
{
	static char dummy_result;
	
	printf("Server: delete_array_1 called - index: %d\n", *argp);
	delete_svc(*argp);
	
	return (void *) &dummy_result;
}
