/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"


void
date_prog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char * *result_2;
	long  str_date_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATE_PROG, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// Call bin_date_1 to get current time
	result_1 = bin_date_1(NULL, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Binary date from server: %ld\n", *result_1);
		
		// Use the binary date to get string representation
		str_date_1_arg = *result_1;
		result_2 = str_date_1(&str_date_1_arg, clnt);
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("String date from server: %s\n", *result_2);
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *request;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	date_prog_1 (host);
exit (0);
}
