/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "date.h"

bool_t
xdr_insert_args (XDR *xdrs, insert_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->element))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	return TRUE;
}
