/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"


void
date_prog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char * *result_2;
	long  str_date_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATE_PROG, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	// Call bin_date_1 to get current time
	result_1 = bin_date_1(NULL, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("Binary date from server: %ld\n", *result_1);
		
		// Use the binary date to get string representation
		str_date_1_arg = *result_1;
		result_2 = str_date_1(&str_date_1_arg, clnt);
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		} else {
			printf("String date from server: %s\n", *result_2);
		}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	// Create RPC client connection
	CLIENT *clnt = clnt_create(host, DATE_PROG, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	
	if(argc >= 3 && strcmp(argv[2], "insert") == 0){
		insert_args args;
		args.element = atoi(argv[3]);  
		args.index = atoi(argv[4]);
		insert_array_1(&args, clnt);
		printf("Inserted element %d at index %d\n", args.element, args.index);
	}
	else if(argc >= 3 && strcmp(argv[2], "retrieve") == 0){
		int index = atoi(argv[3]);  
		int *result = retrieve_array_1(&index, clnt);
		if (result != NULL) {
			printf("Retrieved value: %d\n", *result);
		} else {
			printf("RPC call failed\n");
		}
	}
	else if(argc >= 3 && strcmp(argv[2], "delete") == 0){
		int index = atoi(argv[3]);  
		delete_array_1(&index, clnt);
		printf("Deleted element at index %d if that index was valid\n", index);
	}

	
	clnt_destroy(clnt);

	//date_prog_1 (host);
exit (0);
}
